const WebglConst = {
    FRONT: "FRONT",
    BACK: "BACK",

    LEQUAL: "LEQUAL",
    LESS: "LESS",
    ALWAYS: "ALWAYS",
    NEVER: "NEVER",
    EQUAL: "EQUAL",
    NOTEQUAL: "NOTEQUAL",
    GEQUAL: "GEQUAL",
    GREATER: "GREATER",

    KEEP: "KEEP",
    REPLACE: "REPLACE",
    INCR: "INCR",
    INCR_WRAP: "INCR_WRAP",
    DECR: "DECR",
    DECR_WRAP: "DECR_WRAP",
    INVERT: "INVERT",

    ZERO: "ZERO",
    ONE: "ONE",
    SRC_COLOR: "SRC_COLOR",
    ONE_MINUS_SRC_COLOR: "ONE_MINUS_SRC_COLOR",
    DST_COLOR: "DST_COLOR",
    ONE_MINUS_DST_COLOR: "ONE_MINUS_DST_COLOR",
    SRC_ALPHA: "SRC_ALPHA",
    ONE_MINUS_SRC_ALPHA: "ONE_MINUS_SRC_ALPHA",
    DST_ALPHA: "DST_ALPHA",
    ONE_MINUS_DST_ALPHA: "ONE_MINUS_DST_ALPHA",
    CONSTANT_COLOR: "CONSTANT_COLOR",
    ONE_MINUS_CONSTANT_COLOR: "ONE_MINUS_CONSTANT_COLOR",
    CONSTANT_ALPHA: "CONSTANT_ALPHA",
    ONE_MINUS_CONSTANT_ALPHA: "ONE_MINUS_CONSTANT_ALPHA",

    FUNC_ADD:"FUNC_ADD",
    FUNC_SUBTRACT:"FUNC_SUBTRACT",
    FUNC_REVERSE_SUBTRACT:"FUNC_REVERSE_SUBTRACT",

    //texture
    CLAMP_TO_EDGE:"CLAMP_TO_EDGE",
    REPEAT:"REPEAT"

};
export default WebglConst
