const GLSLConst =  {
    USE_DIFFUSE_MAP:"#define USE_DIFFUSE_MAP\n",
    USE_DIFFUSE_MAP_CUBE:"#define USE_DIFFUSE_MAP_CUBE\n",
    USE_SPECULAR_MAP:"#define USE_SPECULAR_MAP\n",
    USE_SPECULAR_MAP_CUBE:"#define USE_SPECULAR_MAP_CUBE\n",

    USE_METALLIC_MAP:"#define USE_METALLIC_MAP\n",
    USE_ROUGHNESS_MAP:"#define USE_ROUGHNESS_MAP\n",
    USE_AO_MAP:"#define USE_AO_MAP\n",
    USE_NORMAL_MAP:"#define USE_NORMAL_MAP\n",
};

export default GLSLConst
